### ISSUE TITLE
Page iteration

### ISSUE THREAD

**Issue by trusteddev** [Files-com/files-sdk-python#1]
Hi, I'm using this library with flask to display file counts for any directory containing the word 'LOA', the page refreshes itself every 30 seconds. I have a problem with one directory which has 2805 files, this displays correctly for the first iteration, then every subsequent one it displays 805. I took off the .auto_paging_iter() from the file listing and it displays 1000 files, (I take it that is for one page?), I may be missing something obvious with this.

Have attached a snippet from my routes.py to show what I have done:

today = str(date.today())
api_key = os.environ.get("API_KEY")
#login to Files.com
files_sdk.set_api_key(api_key)
list_obj = files_sdk.list_for('/')

def getFileNumbers(list_obj):
       
 
    #get loa directories
    dir_dict = {}
    directories = []
    
    for f in list_obj.auto_paging_iter():
        if "LOA" in f.path.upper():
            directories.append(f.path)
       

    #get file numbers in directories
    for dir in directories:
        list_obj = files_sdk.list_for(dir)
        count = 0
        today_count = 0
        no_files = []
            
        for file in list_obj.auto_paging_iter():
            
            count += 1

            #get files uploaded today
            today_file = file.mtime[0:10]
                    
            if today_file == today:
                today_count += 1

        print(count)
        no_files.append(count)
        no_files.append(today_count)
        dir_dict[dir] = no_files
        

    
    return dir_dict

@app.route('/')
@app.route('/index')
@login_required
def index():    
    
    #api_key = app.config.get('api_key')

    return render_template('index.html', dir_dict = getFileNumbers(list_obj))

**Comment by trusteddev** [comment]
Tried the function outside flask and the same happened, so maybe a problem with how I am using auto_page_iter().

**Comment by bombino** [comment]
Hi,

Thanks for reporting this.  Our Python SDK team will be looking into this and responding soon!

**Comment by bombino** [comment]
Actually, I hear from Matt at our Customer success team that he was able to get you handled.  I'll go ahead and close this issue.
