### ISSUE TITLE
Release policy and stability expectations?

### ISSUE THREAD

**Issue by truthdoug** [Files-com/files-sdk-python#2]
From the frequency of releases for this project, it appears that your continuous integration process generates a new release on most, if not all, commits. 

Can you document the release policy for this package? I'm hesitant to include a package that publishes so quickly without any indication of what's changed or fixed.

**Comment by truthdoug** [comment]
Part of the issue is not excluding `.pyc` files in `.gitignore`

**Comment by romcart** [comment]
Hello @truthdoug,

We follow a versioning scheme for our SDKs that's similar to the one used by AWS and other cloud providers, where our API changes more often than our python SDK code. The release numbering scheme that we use (which increments on updates to our API) results in more patch-level versions, but it's not an indicator of python-specific changes.

With regard to the `.gitignore`, this has been updated to exclude `.pyc` files. 

We appreciate the feedback. If we can be of assistance with SDK usage, please feel free to reach out to support@files.com.

Best,
Justin Sinclair
Files.com

**Comment by truthdoug** [comment]
Thanks for the update. 

I see the change to the `.gitignore` file a week ago but looking at [the most recent commit](https://github.com/Files-com/files-sdk-python/commit/2838da8925d18db8b44371ad4f64b00a9332f350), it's almost entirely `.pyc` files. Is your CI system running something like `git add -f` for these files?

**Comment by truthdoug** [comment]
A colleague reminded me that changing the `.gitignore` doesn't cause files that are already checked in to be ignored.

You'd need to `git rm` these

**Comment by truthdoug** [comment]
With all the noise of the `pyc` files committed a dozen times each day, it's hard to discern what the changes are from release to release.

**Comment by romcart** [comment]
Hello @truthdoug,

We have deployed an update to our SDK release process that removes the noisy .pyc files. These files should no longer be included in SDK releases going forward, so the diffs will be much easier to review for substantive changes.

Thank you again for your feedback!

Best,
Justin Sinclair
Files.com

**Comment by truthdoug** [comment]
ah, much calmer!
