### ISSUE TITLE
The definition of File class is truncated

### ISSUE THREAD

**Issue by casimir** [Files-com/files-sdk-python#3]
Hello, I was reviewing this SDK to replace our custom implementation but got an issue with the `File` class. I was under the impression that some methods were missing.

Diving in the sources I found what looks like a code generation bug. Some functions are inserted in the class definition having for effect to discard the following methods definitions: https://github.com/Files-com/files-sdk-python/blob/41a7deef6cd3d77c26372edc60b8abd8cb4b2f50/files_sdk/models/file.py#L261-L324

![image](https://user-images.githubusercontent.com/879004/126307395-c8ecce8c-3182-4bde-a4e2-ca3aba04b690.png)

**Comment by bombino** [comment]
Hi,

This should be solved now.  Please advise if you still have issues.

**Comment by casimir** [comment]
Hello, thanks for your answer. Sadly, the issue is still the same.

**Comment by bombino** [comment]
Wow, thanks for the update.  Our team took another look at this and pushed another fix, which is shipping now.  Please give this a try.

**Comment by casimir** [comment]
Judging by the commit's diff I'd say it's all good. Thank for the fix!
