### ISSUE TITLE
module 'files_sdk.models.file_action' has no attribute 'begin_upload'

### ISSUE THREAD

**Issue by cinguva** [Files-com/files-sdk-python#4]
Having issue while uploading file using Files.com package on windows OS

**Comment by NovellGit** [comment]
Hello,

Thank you for taking the time to file this issue.

We are happy to report that we have deployed a fix. 

We would love to hear more about how you are using the Python SDK. If you are willing, please send an authenticated ticket via the web interface or email us at support@files.com. You can submit a support request using the Contact Support option in the top-right menu of the web interface. You access the menu by clicking on your user name.

**Comment by cinguva** [comment]
What was the issue and fix?
