### ISSUE TITLE
Incorrect info in your Docs

### ISSUE THREAD

**Issue by greg12579** [Files-com/files-sdk-python#5]
When writing string to file 
should be files_sdk.file.open("foo.txt", 'w')    

NOT "wb". wb is for byte data. Need to fix docs to reflect. 

Docs say "wb" for both byte and string.
files_sdk.file.open("foo.txt", 'wb')

**Comment by Files-Michael** [comment]
Thank you for taking the time to file this issue.

For the quickest investigation into this issue, please send an authenticated support ticket through the Files.com web interface. You can submit a support request using the Contact Support option in the top-right menu of the web interface. You access the menu by clicking on your user name.
